version: '3.8'
services:
  item-app:
    image: ghcr.io/f1dz/item-app:master
    container_name: item-app
    depends_on: 
      - item-db
    ports:
      - 80:8080
  item-db:
    image: mongo:3
    container_name: item-db
    volumes:
      - app-db:/data/db
volumes:
  app-db: