#publish your docker image to github container registry
name: publish
on: [push]
jobs:
  publish-item-app-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build the item-app Docker image
        run: |
          docker build . --tag ghcr.io/f1dz/item-app:latest
          docker run ghcr.io/f1dz/item-app:latest
          docker push ghcr.io/f1dz/item-app:latest